import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

type AdminLanguage = "fr" | "ar";

type Dictionary = Record<string, string>;

interface AdminLanguageContextType {
  language: AdminLanguage;
  setLanguage: (lang: AdminLanguage) => void;
  dir: "ltr" | "rtl";
  t: (key: string) => string;
}

const STORAGE_KEY = "classimo_admin_language";

const translations: Record<AdminLanguage, Dictionary> = {
  fr: {
    "common.loading": "Chargement...",
    "common.cancel": "Annuler",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.create": "Creer",
    "common.update": "Mettre a jour",
    "common.searchProducts": "Rechercher des produits...",
    "common.searchCustomers": "Rechercher des clients...",
    "common.viewAll": "Voir tout",
    "common.joined": "Inscrit",
    "common.active": "actif",
    "common.new": "nouveau",
    "nav.dashboard": "Tableau de bord",
    "nav.products": "Produits",
    "nav.categories": "Categories",
    "nav.orders": "Commandes",
    "nav.customers": "Clients",
    "nav.settings": "Parametres",
    "admin.panel": "Panneau admin",
    "admin.alerts": "Alertes",
    "admin.logout": "Deconnexion",
    "admin.collapse": "Reduire",
    "admin.openMenu": "Ouvrir le menu",
    "admin.closeSidebar": "Fermer la barre laterale",
    "dashboard.title": "Tableau de bord",
    "dashboard.welcome": "Bon retour! Voici l'etat de votre boutique.",
    "dashboard.totalProducts": "Produits totaux",
    "dashboard.activeProducts": "Produits actifs",
    "dashboard.totalCustomers": "Clients totaux",
    "dashboard.categories": "Categories",
    "dashboard.productsByCategory": "Produits par categorie",
    "dashboard.productsByCategorySub": "Nombre actuel dans votre catalogue",
    "dashboard.latestProducts": "Derniers produits",
    "dashboard.latestProductsSub": "Produits recents ou mis en avant",
    "dashboard.recentCustomers": "Clients recents",
    "dashboard.recentCustomersSub": "Dernieres inscriptions de votre boutique",
    "dashboard.noProducts": "Aucun produit pour le moment",
    "dashboard.noCategories": "Aucune categorie pour le moment",
    "dashboard.noCustomers": "Aucun client pour le moment",
    "dashboard.uncategorized": "Sans categorie",
    "dashboard.price": "Prix",
    "products.title": "Produits",
    "products.inventoryCount": "produits en stock",
    "products.addCategory": "Ajouter une categorie",
    "products.addProduct": "Ajouter un produit",
    "products.none": "Aucun produit pour le moment",
    "products.noneSub": "Ajoutez votre premier produit pour commencer",
    "products.product": "Produit",
    "products.category": "Categorie",
    "products.price": "Prix",
    "products.variants": "Variantes",
    "products.stock": "Stock",
    "products.status": "Statut",
    "products.inStock": "en stock",
    "products.lowStock": "stock faible",
    "products.outOfStock": "rupture",
    "products.stockLabel": "en stock",
    "categories.title": "Categories",
    "categories.subtitle": "Gerez les categories de produits",
    "categories.addCategory": "Ajouter une categorie",
    "categories.none": "Aucune categorie pour le moment",
    "categories.noneSub": "Creez votre premiere categorie pour organiser les produits",
    "categories.productsCount": "produits",
    "categories.editCategory": "Modifier la categorie",
    "categories.addNewCategory": "Ajouter une categorie",
    "categories.nameFr": "Nom (Francais)",
    "categories.nameAr": "Nom (Arabe)",
    "categories.image": "Image de categorie",
    "categories.created": "Categorie creee avec succes",
    "categories.updated": "Categorie mise a jour avec succes",
    "categories.deleted": "Categorie supprimee avec succes",
    "categories.saveError": "Erreur lors de l'enregistrement",
    "categories.deleteError": "Erreur lors de la suppression",
    "customers.title": "Clients",
    "customers.subtitle": "Gerez et consultez les informations clients",
    "customers.export": "Exporter",
    "customers.addCustomer": "Ajouter un client",
    "customers.total": "Total clients",
    "customers.newThisMonth": "Nouveaux ce mois",
    "customers.withEmail": "Avec email",
    "customers.withPhone": "Avec telephone",
    "customers.filters": "Filtres",
    "customers.customer": "Client",
    "customers.phone": "Telephone",
    "customers.status": "Statut",
    "customers.joinDate": "Date d'inscription",
    "customers.viewProfile": "Voir profil",
    "customers.sendEmail": "Envoyer email",
    "orders.title": "Tableau des commandes",
    "orders.subtitle": "Vue globale des commandes et des revenus",
    "orders.exportPdf": "Exporter PDF",
    "orders.today": "Aujourd'hui",
    "orders.week": "Cette semaine",
    "orders.month": "Ce mois",
    "orders.allTime": "Tout",
    "orders.totalOrders": "Total commandes",
    "orders.revenue": "Revenu estime",
    "orders.avgOrderValue": "Valeur moyenne",
    "orders.confirmedCancelled": "confirmes, annulees",
    "orders.revenueSub": "Base sur les prix actuels (hors annulees)",
    "orders.avgSub": "Moyenne par commande",
    "orders.recentOrders": "Commandes recentes",
    "orders.customer": "Client",
    "orders.product": "Produit",
    "orders.location": "Lieu",
    "orders.date": "Date",
    "orders.status": "Statut",
    "orders.items": "Articles",
    "orders.actions": "Actions",
    "orders.pending": "En attente",
    "orders.confirmed": "Confirmee",
    "orders.approved": "Approuvee",
    "orders.processing": "En traitement",
    "orders.delivered": "Livree",
    "orders.cancelled": "Annulee",
    "orders.deleteTitle": "Supprimer la commande ?",
    "orders.deleteDescription": "Voulez-vous vraiment supprimer cette commande ? Cette action est irreversible.",
    "orders.noOrders": "Aucune commande trouvee",
    "orders.noOrdersSub": "Changez le filtre de date ou revenez plus tard.",
    "orders.statusUpdated": "Statut de commande mis a jour",
    "orders.statusUpdateFailed": "Echec de mise a jour du statut",
    "orders.resyncQueued": "Commande ajoutee a la file de synchronisation",
    "orders.resyncFailed": "Echec de resynchronisation",
    "orders.deleted": "Commande supprimee avec succes",
    "orders.deleteFailed": "Echec de suppression de la commande",
    "orders.resyncTitle": "Resynchroniser vers Octomatic",
    "settings.title": "Parametres",
    "settings.subtitle": "Gerez votre compte et les preferences boutique",
  },
  ar: {
    "common.loading": "جار التحميل...",
    "common.cancel": "الغاء",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.create": "انشاء",
    "common.update": "تحديث",
    "common.searchProducts": "ابحث عن المنتجات...",
    "common.searchCustomers": "ابحث عن الزبائن...",
    "common.viewAll": "عرض الكل",
    "common.joined": "انضم",
    "common.active": "نشط",
    "common.new": "جديد",
    "nav.dashboard": "لوحة التحكم",
    "nav.products": "المنتجات",
    "nav.categories": "التصنيفات",
    "nav.orders": "الطلبات",
    "nav.customers": "الزبائن",
    "nav.settings": "الاعدادات",
    "admin.panel": "لوحة الادارة",
    "admin.alerts": "التنبيهات",
    "admin.logout": "تسجيل الخروج",
    "admin.collapse": "طي القائمة",
    "admin.openMenu": "فتح القائمة",
    "admin.closeSidebar": "اغلاق الشريط الجانبي",
    "dashboard.title": "لوحة التحكم",
    "dashboard.welcome": "اهلا بعودتك! هذه حالة متجرك.",
    "dashboard.totalProducts": "اجمالي المنتجات",
    "dashboard.activeProducts": "المنتجات النشطة",
    "dashboard.totalCustomers": "اجمالي الزبائن",
    "dashboard.categories": "التصنيفات",
    "dashboard.productsByCategory": "المنتجات حسب التصنيف",
    "dashboard.productsByCategorySub": "عدد مباشر حسب الكتالوج الحالي",
    "dashboard.latestProducts": "احدث المنتجات",
    "dashboard.latestProductsSub": "منتجات مضافة حديثا او مميزة",
    "dashboard.recentCustomers": "احدث الزبائن",
    "dashboard.recentCustomersSub": "اخر التسجيلات في متجرك",
    "dashboard.noProducts": "لا توجد منتجات حاليا",
    "dashboard.noCategories": "لا توجد تصنيفات حاليا",
    "dashboard.noCustomers": "لا يوجد زبائن حاليا",
    "dashboard.uncategorized": "بدون تصنيف",
    "dashboard.price": "السعر",
    "products.title": "المنتجات",
    "products.inventoryCount": "منتج في المخزون",
    "products.addCategory": "اضافة تصنيف",
    "products.addProduct": "اضافة منتج",
    "products.none": "لا توجد منتجات حاليا",
    "products.noneSub": "اضف اول منتج للبدء",
    "products.product": "المنتج",
    "products.category": "التصنيف",
    "products.price": "السعر",
    "products.variants": "الخيارات",
    "products.stock": "المخزون",
    "products.status": "الحالة",
    "products.inStock": "متوفر",
    "products.lowStock": "مخزون منخفض",
    "products.outOfStock": "نفد",
    "products.stockLabel": "في المخزون",
    "categories.title": "التصنيفات",
    "categories.subtitle": "ادارة تصنيفات المنتجات",
    "categories.addCategory": "اضافة تصنيف",
    "categories.none": "لا توجد تصنيفات حاليا",
    "categories.noneSub": "انشئ اول تصنيف لتنظيم المنتجات",
    "categories.productsCount": "منتج",
    "categories.editCategory": "تعديل التصنيف",
    "categories.addNewCategory": "اضافة تصنيف جديد",
    "categories.nameFr": "الاسم (فرنسي)",
    "categories.nameAr": "الاسم (عربي)",
    "categories.image": "صورة التصنيف",
    "categories.created": "تم انشاء التصنيف بنجاح",
    "categories.updated": "تم تحديث التصنيف بنجاح",
    "categories.deleted": "تم حذف التصنيف بنجاح",
    "categories.saveError": "خطأ في حفظ التصنيف",
    "categories.deleteError": "خطأ في حذف التصنيف",
    "customers.title": "الزبائن",
    "customers.subtitle": "ادارة وعرض معلومات الزبائن",
    "customers.export": "تصدير",
    "customers.addCustomer": "اضافة زبون",
    "customers.total": "اجمالي الزبائن",
    "customers.newThisMonth": "الجدد هذا الشهر",
    "customers.withEmail": "مع بريد",
    "customers.withPhone": "مع هاتف",
    "customers.filters": "فلاتر",
    "customers.customer": "الزبون",
    "customers.phone": "الهاتف",
    "customers.status": "الحالة",
    "customers.joinDate": "تاريخ الانضمام",
    "customers.viewProfile": "عرض الملف",
    "customers.sendEmail": "ارسال بريد",
    "orders.title": "لوحة الطلبات",
    "orders.subtitle": "نظرة عامة على الطلبات والايرادات",
    "orders.exportPdf": "تصدير PDF",
    "orders.today": "اليوم",
    "orders.week": "هذا الاسبوع",
    "orders.month": "هذا الشهر",
    "orders.allTime": "كل الفترات",
    "orders.totalOrders": "اجمالي الطلبات",
    "orders.revenue": "الايراد المتوقع",
    "orders.avgOrderValue": "متوسط قيمة الطلب",
    "orders.confirmedCancelled": "مؤكد، ملغي",
    "orders.revenueSub": "حسب الاسعار الحالية (بدون الملغية)",
    "orders.avgSub": "متوسط لكل طلب",
    "orders.recentOrders": "احدث الطلبات",
    "orders.customer": "الزبون",
    "orders.product": "المنتج",
    "orders.location": "المكان",
    "orders.date": "التاريخ",
    "orders.status": "الحالة",
    "orders.items": "الكمية",
    "orders.actions": "الاجراءات",
    "orders.pending": "قيد الانتظار",
    "orders.confirmed": "مؤكد",
    "orders.approved": "مقبول",
    "orders.processing": "قيد المعالجة",
    "orders.delivered": "تم التسليم",
    "orders.cancelled": "ملغي",
    "orders.deleteTitle": "حذف الطلب؟",
    "orders.deleteDescription": "هل تريد حذف هذا الطلب؟ لا يمكن التراجع عن هذا الاجراء.",
    "orders.noOrders": "لا توجد طلبات",
    "orders.noOrdersSub": "جرب تغيير فلتر التاريخ او عد لاحقا.",
    "orders.statusUpdated": "تم تحديث حالة الطلب",
    "orders.statusUpdateFailed": "فشل تحديث حالة الطلب",
    "orders.resyncQueued": "تمت اضافة الطلب لقائمة المزامنة",
    "orders.resyncFailed": "فشل اعادة المزامنة",
    "orders.deleted": "تم حذف الطلب بنجاح",
    "orders.deleteFailed": "فشل حذف الطلب",
    "orders.resyncTitle": "اعادة مزامنة مع Octomatic",
    "settings.title": "الاعدادات",
    "settings.subtitle": "ادارة الحساب وتفضيلات المتجر",
  },
};

const AdminLanguageContext = createContext<AdminLanguageContextType | undefined>(undefined);

export const AdminLanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<AdminLanguage>("fr");

  useEffect(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored === "fr" || stored === "ar") {
      setLanguageState(stored);
    }
  }, []);

  const setLanguage = (lang: AdminLanguage) => {
    setLanguageState(lang);
    localStorage.setItem(STORAGE_KEY, lang);
  };

  const value = useMemo<AdminLanguageContextType>(() => {
    const dict = translations[language];
    return {
      language,
      setLanguage,
      dir: language === "ar" ? "rtl" : "ltr",
      t: (key: string) => dict[key] || key,
    };
  }, [language]);

  return <AdminLanguageContext.Provider value={value}>{children}</AdminLanguageContext.Provider>;
};

export const useAdminLanguage = () => {
  const ctx = useContext(AdminLanguageContext);
  if (!ctx) {
    throw new Error("useAdminLanguage must be used within AdminLanguageProvider");
  }
  return ctx;
};
